import keyMirror from '../utils/keyMirror';

export default keyMirror({

	/**
	* Auth Login
	*/
	REQUEST_LOGIN_USER_SUCCESS: null,
	REQUEST_LOGIN_USER_ERROR: null,
	REQUEST_RESET_PASSWORD_SUCCESS: null,
	REQUEST_RESET_PASSWORD_ERROR: null,
	SET_AFTER_LOGIN_REDIRECTION_URL: null,
	RESET_AFTER_LOGIN_REDIRECTION_URL: null,

	LOGOUT: null,
	LOGOUT_SUCCESS: null,
	LOGOUT_FAIL: null,

	REQUEST_REFRESH_JWT_SUCCESS: null,
	REQUEST_REFRESH_JWT_ERROR: null,
	UNAUTHORIZED_USER: null,

	SET_AREAS_CATEGORIES: null,
	/**
	* Users
	*/
	GET_PROFILE: null,
	GET_PROFILE_SUCCESS: null,
	GET_PROFILE_ERROR: null,

	GET_MEMBERS_SUCCESS: null,
	GET_MEMBERS_ERROR: null,



	/**
	* Company
	*/
});
