import keyMirror from '../utils/keyMirror';

export default keyMirror({

	/**
	* Auth Login
	*/
	REQUEST_LOGIN_USER_SUCCESS: null,
	REQUEST_LOGIN_USER_ERROR: null,
	REQUEST_RESET_PASSWORD_SUCCESS: null,
	REQUEST_RESET_PASSWORD_ERROR: null,
	RESET_PASSWORD_SUCCESS: null,
	RESET_PASSWORD_ERROR: null,
	SET_AFTER_LOGIN_REDIRECTION_URL: null,
	RESET_AFTER_LOGIN_REDIRECTION_URL: null,

	LOGOUT: null,
	LOGOUT_SUCCESS: null,
	LOGOUT_FAIL: null,

	REQUEST_REFRESH_JWT_SUCCESS: null,
	REQUEST_REFRESH_JWT_ERROR: null,
	UNAUTHORIZED_USER: null,

	SET_AREAS_CATEGORIES: null,
	SET_SERVICE_DESCRIPTION: null,

	SUBMIT_SERVICE_SUCCESS: null,
	SUBMIT_SERVICE_ERROR: null,
	SUBMIT_SERVICE_SUCCESS: null,
	SUBMIT_SERVICE_ERROR: null,
	DELETE_SERVICE_SUCCESS: null,
	DELETE_SERVICE_ERROR: null,

	GET_SERVICES_SUCCESS: null,
	GET_SERVICES_ERROR: null,
	GET_SERVICES_BYID_SUCCESS: null,
	GET_SERVICES_BYID_ERROR: null,
	SET_SERVICE_USER_DATA: null,
	GET_MYINFO_SUCCESS: null,
	GET_MYINFO_ERROR: null,
	ACCEPT_SERVICE_SUCCESS: null,
	ACCEPT_SERVICE_ERROR: null,
	REJECT_SERVICE_SUCCESS: null,
	REJECT_SERVICE_ERROR: null,
	UPDATE_SERVICE_SUCCESS: null,
	UPDATE_SERVICE_ERROR: null,

	GET_USERS_SUCCESS: null,
	GET_USERS_ERROR: null,
	UPDATE_SALES_SUCCESS: null,
	UPDATE_SALES_ERROR: null,

	/**
	* Registration
	*/
	SIGNUP_USER: null,
	SIGNUP_USER_SUCCESS: null,
	SIGNUP_USER_ERROR: null,
	SIGNUP_EMAIL_AVAILABLE_SUCCESS: null,
	SIGNUP_EMAIL_AVAILABLE_ERROR: null,

	SIGNUP_STEP2_SUCCESS: null,
	SIGNUP_STEP2_ERROR: null,


	/**
	* Users
	*/
	GET_PROFILE: null,
	GET_PROFILE_SUCCESS: null,
	GET_PROFILE_ERROR: null,

	GET_MEMBERS_SUCCESS: null,
	GET_MEMBERS_ERROR: null,

	UPDATE_PROFILE_SUCCESS: null,
	UPDATE_PROFILE_ERROR: null,



	/**
	* Company
	*/
});
